networks:
  next-template-network:
    name: next-template-network

services:
  next-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
      - .env.local
    volumes:
      - ..:/workspace/app:cached
      - /workspace/app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - next-template-network
