networks:
  next-template-network:
    name: next-template-network

services:
  next:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace/app:cached
      - /workspace/app/node_modules
    command: tail -f /dev/null
    ports:
      - "3000:3000"
    networks:
      - next-template-network
    restart: unless-stopped
